title: Fondinfo
description: Programming lab @ DII, UniPR
google_analytics: 
show_downloads: true
theme: jekyll-theme-architect

github:
  zip_url: https://github.com/tomamic/fondinfo/archive/master.zip
  tar_url: https://github.com/tomamic/fondinfo/archive/master.tar.gz

gems:
  - jekyll-mentions
